namespace Exercise;

public class TestException
{
    /**
     * TODO: test class Triangle
     * 
     * Test 2 scenarios:
     * 1. Create a valid triangle and then display 
     * its perimeter and area. 
     * 
     * 2. Create an invalid triangle and then display
     * its perimeter and area.
     * What happens to the program?
     * 
     * Then:
     * 3. Put the creating triangles part into a 
     * try-catch block, then display the error 
     * message if there is any exception.
     * 
     * In the 2nd scenario, can the triangle's perimeter 
     * and area be displayed?
     * 
     */
    // static void Main(string[] args)
    // {
    //     try
    //     {
    //         var validTriangle = new Triangle(3, 4, 5);
    //         Console.WriteLine(validTriangle);
    //
    //         var invalidTriangle = new Triangle(3, 2, 7);
    //         Console.WriteLine(invalidTriangle);
    //     }
    //     catch (BadTriangleException e)
    //     {
    //         Console.WriteLine(e.Message);
    //     }
    // }
}